# -*- mode:python -*-
#
# ======================= START OF LICENSE NOTICE =======================
#   Copyright (C) 2021 Kang Ning, NCIC, ICT, CAS.
#   All Rights Reserved.
#
#   NO WARRANTY. THE PRODUCT IS PROVIDED BY DEVELOPER "AS IS" AND ANY
#   EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
#   PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL DEVELOPER BE LIABLE FOR
#   ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
#   GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
#   IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#   OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THE PRODUCT, EVEN
#   IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# ======================== END OF LICENSE NOTICE ========================
#   Primary Author: Kang Ning
#       <kangning18z@ict.ac.cn>
#   Date: 2021.07.08

#
# @file
# Han Gu RNIC register defination declaration.
#

Import('*')

SimObject('Xdr.py')

# NIC controller
Source('nic_ctrl.cc')
Source('libibv.cc')
Source('ibv_test_client.cc')
Source('ibv_test_server.cc')


DebugFlag('NicCtrl')
DebugFlag('MemAlloc')
DebugFlag('Ibv')
DebugFlag('IbvTestClient')
DebugFlag('IbvTestServer')

CompoundFlag('XDR', ['NicCtrl', 'MemAlloc', 'Ibv', 'IbvTestClient', 'IbvTestServer'])
